import { useCallback, useEffect, useState } from "react";
import { Heart, MessageCircle, Repeat2, RefreshCw, Loader2, TrendingUp, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Link } from "wouter";
import { getInitials } from "@/lib/utils";
import { BadgeList } from "@/lib/badges";

const API = "https://pulse-api-proxy.joeldavidengelman.workers.dev";
async function api(path: string) { const r = await fetch(`${API}${path}`, { credentials: "include" }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || `HTTP ${r.status}`); return d; }
function ago(v: string) { const s = Math.max(1, Math.floor((Date.now() - new Date(v).getTime()) / 1000)); if (s < 60) return `${s}s`; if (s < 3600) return `${Math.floor(s/60)}m`; if (s < 86400) return `${Math.floor(s/3600)}h`; return `${Math.floor(s/86400)}d`; }

export default function Home() {
  const [posts, setPosts] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setPosts(await api("/api/feed?mode=popular")); } catch(e:any) { setError(e?.message || "Couldn't load popular posts."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  return <div className="w-full h-full overflow-y-auto custom-scrollbar"><div className="max-w-2xl mx-auto px-4 py-7 md:py-10">
    <div className="flex items-center justify-between mb-7"><div><div className="flex items-center gap-2"><TrendingUp className="w-6 h-6 text-primary"/><h1 className="text-3xl font-bold">Home</h1></div><p className="text-muted-foreground text-sm mt-1">Popular on Pulse right now.</p></div><Button variant="ghost" size="icon" onClick={load} className="cursor-pointer" title="Refresh"><RefreshCw className={`w-5 h-5 ${loading ? "animate-spin" : ""}`}/></Button></div>
    <Link href="/social" className="block bg-primary/10 border border-primary/20 rounded-2xl p-4 mb-6 hover:bg-primary/15 transition-colors cursor-pointer"><div className="flex items-center gap-3"><Sparkles className="w-5 h-5 text-primary"/><div><p className="font-semibold">Pulse Social</p><p className="text-sm text-muted-foreground">Create posts, share photos, add music, follow people and repost.</p></div></div></Link>
    {error && <div className="mb-4 rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}
    {loading ? <div className="flex justify-center py-16"><Loader2 className="w-7 h-7 text-primary animate-spin"/></div> : posts.length === 0 ? <div className="bg-card border border-border rounded-2xl p-10 text-center text-muted-foreground">No popular posts yet. Be the first!</div> : posts.map((p:any) => <article key={p.id} className="bg-card border border-border rounded-2xl p-4 mb-4 shadow-sm"><div className="flex items-center gap-3"><Avatar className="w-10 h-10"><AvatarImage src={p.user?.avatarUrl || ""}/><AvatarFallback>{getInitials(p.user?.displayName || "?")}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex items-center min-w-0"><p className="font-semibold truncate">{p.user?.displayName}</p><BadgeList user={p.user} compact /></div><p className="text-xs text-muted-foreground">@{p.user?.username} · {ago(p.createdAt)}</p></div></div>{p.content&&<p className="whitespace-pre-wrap mt-4 text-sm leading-6">{p.content}</p>}{p.media?.image&&<img src={p.media.image} className="mt-3 rounded-xl max-h-[380px] w-full object-cover" style={{filter:p.media.filter || "none"}}/>}{p.media?.music&&<div className="mt-3 flex items-center gap-3 bg-secondary/70 rounded-xl p-3"><div className="min-w-0"><p className="font-semibold text-sm truncate">{p.media.music.title}</p><p className="text-xs text-muted-foreground">{p.media.music.artist}</p></div><audio controls preload="none" src={p.media.music.previewUrl} className="ml-auto max-w-[180px]"/></div>}{p.repostOf&&<div className="mt-3 rounded-xl border border-border bg-background/50 p-3"><p className="text-xs text-muted-foreground mb-1">Reposted from @{p.repostOf.user?.username}</p><p className="text-sm whitespace-pre-wrap">{p.repostOf.content}</p>{p.repostOf.image&&<img src={p.repostOf.image} className="mt-2 rounded-lg max-h-60 w-full object-cover"/>}</div>}<div className="flex items-center gap-5 mt-4 text-sm text-muted-foreground"><span className="inline-flex items-center gap-1"><Heart className="w-4 h-4"/> {p.likeCount||0}</span><span className="inline-flex items-center gap-1"><MessageCircle className="w-4 h-4"/> {p.commentCount||0}</span><span className="inline-flex items-center gap-1"><Repeat2 className="w-4 h-4"/> Reposts</span></div></article>)}
  </div></div>;
}
