import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { Eye, EyeOff, Plus, Trash2, UserRound, Lock, LogOut, Palette, Check, ShieldCheck, UserX } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/hooks/use-auth";
import { useTheme, THEME_OPTIONS, type Theme } from "@/hooks/use-theme";
import { useLogout } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { PulseIconPicker } from "@/components/pulse-icon-picker";

const ACCOUNT_API="https://lbphvoonoxpbvpovozuo.supabase.co/functions/v1/pulse-account";
const TOKEN_KEY="pulse-supabase-access-token";
const ACCOUNTS_KEY="pulse-saved-accounts";
function savedAccounts():string[]{try{return JSON.parse(localStorage.getItem(ACCOUNTS_KEY)||"[]")}catch{return []}}
function headers():HeadersInit{const t=localStorage.getItem(TOKEN_KEY);return t?{Authorization:`Bearer ${t}`,"Content-Type":"application/json"}:{"Content-Type":"application/json"}}

export default function Settings(){
 const {user}=useAuth();const [,setLocation]=useLocation();const logout=useLogout();const queryClient=useQueryClient();const {theme,setTheme}=useTheme();
 const [accounts,setAccounts]=useState<string[]>([]),[current,setCurrent]=useState("");const [newPassword,setNewPassword]=useState(""),[currentPassword,setCurrentPassword]=useState("");const [showCurrent,setShowCurrent]=useState(false),[showNew,setShowNew]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");const [searchOnly,setSearchOnly]=useState(false),[discoverable,setDiscoverable]=useState(true),[privacyBusy,setPrivacyBusy]=useState(false),[privacyMessage,setPrivacyMessage]=useState("");const [deleteText,setDeleteText]=useState(""),[deleteBusy,setDeleteBusy]=useState(false),[deleteError,setDeleteError]=useState("");
 useEffect(()=>{const list=savedAccounts();if(user?.username&&!list.includes(user.username)){list.unshift(user.username);localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(list.slice(0,8)))}setAccounts(list);setCurrent(user?.username||"");setSearchOnly(Boolean((user as any)?.messageSearchOnly));setDiscoverable((user as any)?.discoverable!==false)},[user?.username,(user as any)?.messageSearchOnly,(user as any)?.discoverable]);
 const remove=(name:string)=>{const list=accounts.filter(x=>x.toLowerCase()!==name.toLowerCase());setAccounts(list);localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(list))};
 const switchAccount=(name:string)=>{if(name.toLowerCase()===user?.username?.toLowerCase())return;logout.mutate(undefined,{onSuccess:()=>{localStorage.removeItem(TOKEN_KEY);queryClient.clear();setLocation(`/login?username=${encodeURIComponent(name)}`)}})};
 const changePassword=async(e:React.FormEvent)=>{e.preventDefault();setError("");setMessage("");if(newPassword.length<8){setError("New password must be at least 8 characters.");return}if(!/[A-Za-z]/.test(newPassword)||!/[0-9]/.test(newPassword)){setError("New password must contain at least one letter and one number.");return}setBusy(true);try{const r=await fetch(`${ACCOUNT_API}/password`,{method:"POST",headers:headers(),body:JSON.stringify({currentPassword,newPassword})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Couldn't change password.");setCurrentPassword("");setNewPassword("");setMessage("Password changed successfully.")}catch(e:any){setError(e.message||"Couldn't change password.")}finally{setBusy(false)}};
 const savePrivacy=async(patch:{messageSearchOnly?:boolean;discoverable?:boolean})=>{setPrivacyBusy(true);setPrivacyMessage("");try{const r=await fetch(`${ACCOUNT_API}/privacy`,{method:"PATCH",headers:headers(),body:JSON.stringify(patch)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Couldn't update privacy settings.");setSearchOnly(Boolean(d.messageSearchOnly));setDiscoverable(d.discoverable!==false);setPrivacyMessage("Privacy settings saved.");queryClient.invalidateQueries({queryKey:["/api/auth/me"]})}catch(e:any){setPrivacyMessage(e.message||"Couldn't update privacy settings.")}finally{setPrivacyBusy(false)}};
 const deleteAccount=async()=>{setDeleteError("");if(deleteText!=="DELETE"){setDeleteError("Type DELETE exactly to confirm account deletion.");return}setDeleteBusy(true);try{const r=await fetch(`${ACCOUNT_API}/delete`,{method:"POST",headers:headers(),body:JSON.stringify({confirm:"DELETE"})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Couldn't delete your account.");localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(ACCOUNTS_KEY);queryClient.clear();setLocation("/login?deleted=1")}catch(e:any){setDeleteError(e.message||"Couldn't delete your account.")}finally{setDeleteBusy(false)}};
 return <div className="w-full h-full overflow-y-auto custom-scrollbar"><div className="max-w-2xl mx-auto px-4 py-8"><h1 className="text-3xl font-bold">Settings</h1><p className="text-muted-foreground mt-1 mb-7">Customize Pulse and manage your account.</p><PulseIconPicker/>
 <section className="glass-panel rounded-3xl p-5 mb-5"><div className="flex items-center gap-3 mb-4"><div className="p-2 rounded-xl bg-primary/10 text-primary"><Palette className="w-5 h-5"/></div><div><h2 className="font-semibold">Themes</h2><p className="text-xs text-muted-foreground">Choose a complete visual style.</p></div></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{THEME_OPTIONS.map(o=><button key={o.id} onClick={()=>setTheme(o.id as Theme)} className={`group relative overflow-hidden rounded-2xl border text-left transition-all hover:scale-[1.02] ${theme===o.id?"border-primary ring-2 ring-primary/30":"border-border"}`}><div className="h-24 relative overflow-hidden" style={o.image?{backgroundImage:`linear-gradient(135deg,rgba(0,0,0,.28),rgba(0,0,0,.55)),url(${o.image})`,backgroundSize:"cover",backgroundPosition:"center"}:{background:o.id==="light"?"linear-gradient(135deg,#eef2f7,#fff)":"linear-gradient(135deg,#05070d,#17202b)"}}>{theme===o.id&&<span className="absolute top-2 right-2 grid place-items-center w-7 h-7 rounded-full bg-primary text-primary-foreground"><Check className="w-4 h-4"/></span>}</div><div className="p-3 bg-card/70"><p className="font-medium text-sm">{o.name}</p><p className="text-[11px] text-muted-foreground mt-0.5">{o.description}</p></div></button>)}</div></section>
 <section className="glass-panel rounded-3xl p-5 mb-5"><div className="flex items-center gap-3 mb-4"><UserRound className="w-5 h-5 text-primary"/><div><h2 className="font-semibold">Accounts</h2><p className="text-xs text-muted-foreground">Keep multiple Pulse accounts on this device.</p></div></div><div className="space-y-2">{accounts.map(name=><div key={name} className="flex items-center gap-3 p-3 rounded-2xl bg-secondary/35"><div className="w-9 h-9 rounded-full bg-primary/10 grid place-items-center text-primary"><UserRound className="w-4 h-4"/></div><div className="flex-1"><p className="font-medium">@{name}</p>{name.toLowerCase()===current.toLowerCase()&&<p className="text-[11px] text-primary">Current account</p>}</div>{name.toLowerCase()!==current.toLowerCase()&&<Button variant="outline" size="sm" onClick={()=>switchAccount(name)}>Switch</Button>}<button onClick={()=>remove(name)} title="Remove saved account" className="p-2 rounded-xl text-muted-foreground hover:text-destructive hover:bg-destructive/10"><Trash2 className="w-4 h-4"/></button></div>)}</div><Button className="mt-4" variant="outline" onClick={()=>setLocation("/login?add=1")}><Plus className="w-4 h-4 mr-2"/>Add another account</Button></section>
 <section className="glass-panel rounded-3xl p-5 mb-5"><div className="flex items-center gap-3 mb-4"><div className="p-2 rounded-xl bg-primary/10 text-primary"><ShieldCheck className="w-5 h-5"/></div><div><h2 className="font-semibold">Privacy & safety</h2><p className="text-xs text-muted-foreground">Control discovery and new conversations.</p></div></div><div className="space-y-2"><button type="button" disabled={privacyBusy} onClick={()=>savePrivacy({discoverable:!discoverable})} className={`w-full flex items-center justify-between gap-4 rounded-2xl border p-4 text-left ${discoverable?"border-border bg-secondary/20":"border-primary/40 bg-primary/5"}`}><div><p className="font-medium">Appear in people search</p><p className="text-xs text-muted-foreground mt-1">{discoverable?"People can find you by username or display name.":"Your account is hidden from user discovery."}</p></div><span className={`relative w-12 h-7 rounded-full ${discoverable?"bg-primary":"bg-muted"}`}><span className={`absolute top-1 w-5 h-5 rounded-full bg-white ${discoverable?"translate-x-6":"translate-x-1"}`}/></span></button><button type="button" disabled={privacyBusy} onClick={()=>savePrivacy({messageSearchOnly:!searchOnly})} className={`w-full flex items-center justify-between gap-4 rounded-2xl border p-4 text-left ${searchOnly?"border-primary/40 bg-primary/5":"border-border bg-secondary/20"}`}><div><p className="font-medium">Search-only messaging</p><p className="text-xs text-muted-foreground mt-1">{searchOnly?"People must find you through search before starting a chat.":"People can start chats with you normally."}</p></div><span className={`relative w-12 h-7 rounded-full ${searchOnly?"bg-primary":"bg-muted"}`}><span className={`absolute top-1 w-5 h-5 rounded-full bg-white ${searchOnly?"translate-x-6":"translate-x-1"}/></span></button></div>{privacyMessage&&<p className="text-sm text-muted-foreground mt-3">{privacyMessage}</p>}<Link href="/safety" className="inline-flex mt-4 text-sm text-primary hover:underline">Open Safety & Privacy Center →</Link></section>
 <section className="glass-panel rounded-3xl p-5 mb-5"><div className="flex items-center gap-3 mb-4"><Lock className="w-5 h-5 text-primary"/><div><h2 className="font-semibold">Password</h2><p className="text-xs text-muted-foreground">Use at least 8 characters with a letter and number.</p></div></div><form onSubmit={changePassword} className="space-y-3"><div className="relative"><Input type={showCurrent?"text":"password"} value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} placeholder="Current password" required/><button type="button" onClick={()=>setShowCurrent(x=>!x)} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-muted-foreground">{showCurrent?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button></div><div className="relative"><Input type={showNew?"text":"password"} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="New password" minLength={8} required/><button type="button" onClick={()=>setShowNew(x=>!x)} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-muted-foreground">{showNew?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button></div>{error&&<p className="text-sm text-destructive">{error}</p>}{message&&<p className="text-sm text-green-600">{message}</p>}<Button type="submit" disabled={busy}>{busy?"Changing…":"Change password"}</Button></form></section>
 <section className="rounded-3xl p-5 mb-8 border border-destructive/30 bg-destructive/5"><div className="flex items-center gap-3 mb-2"><UserX className="w-5 h-5 text-destructive"/><h2 className="font-semibold">Delete account</h2></div><p className="text-sm text-muted-foreground mb-4">Permanently delete your Pulse account. This cannot be undone.</p><div className="flex gap-2"><Input value={deleteText} onChange={e=>setDeleteText(e.target.value)} placeholder="Type DELETE" className="bg-background"/><Button variant="destructive" onClick={deleteAccount} disabled={deleteBusy||deleteText!=="DELETE"}>{deleteBusy?"Deleting…":"Delete account"}</Button></div>{deleteError&&<p className="text-sm text-destructive mt-2">{deleteError}</p>}</section>
 <Link href="/profile" className="inline-flex items-center gap-2 text-sm text-primary hover:underline"><LogOut className="w-4 h-4 rotate-180"/>Back to profile</Link></div></div>;
}