import base from "./index";

export interface Env { DB: D1Database; CORS_ORIGIN?: string; AI?: Ai; }
const SESSION="pulse_session";
function cors(req:Request,env:Env){const h=new Headers({"Access-Control-Allow-Origin":req.headers.get("Origin")||env.CORS_ORIGIN||"https://joelengelman.github.io","Access-Control-Allow-Credentials":"true","Access-Control-Allow-Headers":"Content-Type, Accept, Authorization","Access-Control-Allow-Methods":"GET,POST,PUT,PATCH,DELETE,OPTIONS"});return h}
function json(data:any,status=200,req?:Request,env?:Env){const h=new Headers({"Content-Type":"application/json","Cache-Control":"no-store"});if(req&&env)for(const [k,v] of cors(req,env))h.set(k,v);return new Response(JSON.stringify(data),{status,headers:h})}
function cookie(req:Request){const m=(req.headers.get("Cookie")||"").match(/(?:^|;\s*)pulse_session=([^;]+)/);return m?decodeURIComponent(m[1]):null}
async function me(req:Request,env:Env){const token=cookie(req);if(!token)return null;return env.DB.prepare("SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>? LIMIT 1").bind(token,new Date().toISOString()).first<any>()}
function pub(u:any){return {id:Number(u.id),username:u.username,displayName:u.display_name||u.username,avatarUrl:u.avatar_url||null,bio:u.bio||null,isOnline:Date.now()-new Date(u.last_seen_at||u.updated_at||u.created_at).getTime()<45000,lastSeen:u.last_seen_at||u.updated_at||u.created_at,createdAt:u.created_at,discoverable:u.discoverable!==0,messageSearchOnly:!!u.message_search_only}}
async function ensure(env:Env){await env.DB.batch([env.DB.prepare("CREATE TABLE IF NOT EXISTS communities (id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,description TEXT,owner_id TEXT NOT NULL,created_at TEXT NOT NULL)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS community_members (community_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'member',joined_at TEXT NOT NULL,PRIMARY KEY(community_id,user_id))"),env.DB.prepare("CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,actor_id TEXT,type TEXT NOT NULL,message TEXT NOT NULL,link TEXT,read INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL)")]);try{await env.DB.prepare("ALTER TABLE users ADD COLUMN discoverable INTEGER NOT NULL DEFAULT 1").run()}catch{}}
function id(){return `${Date.now()}${Math.floor(Math.random()*1000)}`}
export default {async fetch(req:Request,env:Env){if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req,env)});await ensure(env);const url=new URL(req.url),path=url.pathname.replace(/\/+$/,'')||'/';const user=await me(req,env);
 if(path.startsWith('/api/')&&!user&&!path.startsWith('/api/auth/'))return json({error:'Not authenticated'},401,req,env);
 if(path==='/api/communities'&&req.method==='GET'){const q=(url.searchParams.get('q')||'').trim();const rows=await env.DB.prepare(q?"SELECT * FROM communities WHERE lower(name) LIKE lower(?) ORDER BY created_at DESC LIMIT 50":"SELECT * FROM communities ORDER BY created_at DESC LIMIT 50").bind(...(q?[`%${q}%`]:[])).all<any>();const out=[];for(const c of rows.results){const n=await env.DB.prepare("SELECT COUNT(*) count FROM community_members WHERE community_id=?").bind(c.id).first<any>();const j=await env.DB.prepare("SELECT 1 FROM community_members WHERE community_id=? AND user_id=?").bind(c.id,user.id).first();out.push({...c,memberCount:Number(n?.count||0),joined:!!j})}return json(out,200,req,env)}
 if(path==='/api/communities'&&req.method==='POST'){const b=await req.json().catch(()=>({}));const name=String(b.name||'').trim().slice(0,60),description=String(b.description||'').trim().slice(0,500);if(!/^[A-Za-z0-9][A-Za-z0-9 _-]{2,59}$/.test(name))return json({error:'Community names must be 3-60 characters.'},400,req,env);const cid=id(),now=new Date().toISOString();try{await env.DB.batch([env.DB.prepare("INSERT INTO communities(id,name,description,owner_id,created_at) VALUES(?,?,?,?,?)").bind(cid,name,description,user.id,now),env.DB.prepare("INSERT INTO community_members(community_id,user_id,role,joined_at) VALUES(?,?,?,?)").bind(cid,user.id,'owner',now)])}catch{return json({error:'That community name is already taken.'},409,req,env)}return json({id:cid,name,description,owner_id:user.id,created_at:now,memberCount:1,joined:true},201,req,env)}
 const cm=path.match(/^\/api\/communities\/([^/]+)\/join$/);if(cm){const cid=cm[1],c=await env.DB.prepare("SELECT * FROM communities WHERE id=?").bind(cid).first<any>();if(!c)return json({error:'Community not found'},404,req,env);if(req.method==='POST'){await env.DB.prepare("INSERT OR IGNORE INTO community_members(community_id,user_id,role,joined_at) VALUES(?,?,?,?)").bind(cid,user.id,'member',new Date().toISOString()).run();return json({joined:true},200,req,env)}if(req.method==='DELETE'){if(String(c.owner_id)===String(user.id))return json({error:'Community owners cannot leave their own community.'},400,req,env);await env.DB.prepare("DELETE FROM community_members WHERE community_id=? AND user_id=?").bind(cid,user.id).run();return json({joined:false},200,req,env)}}
 if(path==='/api/notifications'&&req.method==='GET'){const rows=await env.DB.prepare("SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100").bind(user.id).all<any>();return json(rows.results.map((n:any)=>({...n,id:String(n.id),read:!!n.read,createdAt:n.created_at,actorId:n.actor_id})),200,req,env)}
 if(path==='/api/notifications/read'&&req.method==='POST'){await env.DB.prepare("UPDATE notifications SET read=1 WHERE user_id=?").bind(user.id).run();return json({ok:true},200,req,env)}
 const prof=path.match(/^\/api\/users\/([^/]+)\/public-profile$/);if(prof&&req.method==='GET'){const target=await env.DB.prepare("SELECT * FROM users WHERE lower(username)=lower(?) OR id=? LIMIT 1").bind(prof[1],prof[1]).first<any>();if(!target||target.discoverable===0)return json({error:'Profile not found'},404,req,env);const f=await env.DB.prepare("SELECT COUNT(*) count FROM follows WHERE following_id=?").bind(target.id).first<any>();const g=await env.DB.prepare("SELECT COUNT(*) count FROM follows WHERE follower_id=?").bind(target.id).first<any>();const p=await env.DB.prepare("SELECT * FROM posts WHERE user_id=? ORDER BY created_at DESC LIMIT 50").bind(target.id).all<any>();return json({user:pub(target),followers:Number(f?.count||0),following:Number(g?.count||0),posts:p.results},200,req,env)}
 if(path==='/api/ai/chat'&&req.method==='POST'){const b=await req.json().catch(()=>({}));const prompt=String(b.message||b.prompt||'').trim();if(!prompt||prompt.length>12000)return json({error:'Message must be between 1 and 12000 characters.'},400,req,env);if(!env.AI)return json({error:'Pulse AI is not configured on the API yet.'},503,req,env);const result:any=await env.AI.run('@cf/meta/llama-3.1-8b-instruct',{prompt:`You are Pulse AI, a friendly, safe, age-appropriate assistant inside the Pulse social app. Be concise and helpful.\n\nUser: ${prompt}`});const text=typeof result==='string'?result:(result?.response||result?.result?.response||JSON.stringify(result));return json({response:text,model:'@cf/meta/llama-3.1-8b-instruct'},200,req,env)}
 return base.fetch(req,env as any)} };