export interface Env {
  DB: D1Database;
  CORS_ORIGIN?: string;
}

const SESSION_COOKIE = "pulse_session";
const SESSION_DAYS = 30;

function corsHeaders(request: Request, env: Env): HeadersInit {
  const origin = request.headers.get("Origin");
  const allowed = env.CORS_ORIGIN || "https://joelengelman.github.io";
  return { "Access-Control-Allow-Origin": origin === allowed ? origin : allowed, "Access-Control-Allow-Credentials": "true", "Access-Control-Allow-Headers": "Content-Type, X-Requested-With, Accept, Authorization", "Access-Control-Allow-Methods": "GET,POST,PUT,PATCH,DELETE,OPTIONS", "Access-Control-Max-Age": "86400", "Vary": "Origin" };
}
function json(data: unknown, status = 200, request?: Request, env?: Env, extra?: HeadersInit) { const headers = new Headers({ "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store", ...(extra || {}) }); if (request && env) for (const [key, value] of Object.entries(corsHeaders(request, env))) headers.set(key, value); return new Response(JSON.stringify(data), { status, headers }); }
function error(message: string, status: number, request: Request, env: Env) { return json({ error: message }, status, request, env); }
function parseBody(request: Request): Promise<any> { return request.json().catch(() => ({})); }
function id(): string { return `${Date.now()}${String(Math.floor(Math.random() * 100)).padStart(2, "0")}`; }
function publicUser(row: any, online = false) { const seen = row.last_seen_at || row.updated_at || row.created_at; const fresh = Date.now() - new Date(seen).getTime() < 45000; return { id: Number(row.id), username: row.username, displayName: row.display_name || row.username, avatarUrl: row.avatar_url ?? null, bio: row.bio ?? null, isOnline: fresh, lastSeen: seen, createdAt: row.created_at, messageSearchOnly: !!row.message_search_only, peerId: row.peer_id || null }; }
function getCookie(request: Request, name: string): string | null { const cookie = request.headers.get("Cookie") || ""; const match = cookie.match(new RegExp(`(?:^|;\\s*)${name}=([^;]+)`)); return match ? decodeURIComponent(match[1]) : null; }
function sessionCookie(value: string, maxAge = SESSION_DAYS * 86400): string { return `${SESSION_COOKIE}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=None`; }
async function hashPassword(password: string, salt: string): Promise<string> { const data = new TextEncoder().encode(password); const key = await crypto.subtle.importKey("raw", data, "PBKDF2", false, ["deriveBits"]); const bits = await crypto.subtle.deriveBits({ name: "PBKDF2", salt: new TextEncoder().encode(salt), iterations: 100_000, hash: "SHA-256" }, key, 256); return Array.from(new Uint8Array(bits)).map((b) => b.toString(16).padStart(2, "0")).join(""); }
async function createPasswordHash(password: string): Promise<string> { const salt = crypto.randomUUID(); return `${salt}:${await hashPassword(password, salt)}`; }
async function verifyPassword(password: string, stored: string): Promise<boolean> { const [salt, hash] = stored.split(":", 2); if (!salt || !hash) return false; return (await hashPassword(password, salt)) === hash; }
async function currentUser(request: Request, env: Env): Promise<any | null> { const token = getCookie(request, SESSION_COOKIE); if (!token) return null; return env.DB.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id = s.user_id WHERE s.id = ? AND s.expires_at > ? LIMIT 1`).bind(token, new Date().toISOString()).first<any>(); }
async function requireUser(request: Request, env: Env): Promise<any | null> { return currentUser(request, env); }
async function ensureExtraTables(env: Env) { const columns = await env.DB.prepare(`PRAGMA table_info(users)`).all<any>(); if (!columns.results.some((c: any) => c.name === "message_search_only")) await env.DB.prepare(`ALTER TABLE users ADD COLUMN message_search_only INTEGER NOT NULL DEFAULT 0`).run(); if (!columns.results.some((c: any) => c.name === "peer_id")) await env.DB.prepare(`ALTER TABLE users ADD COLUMN peer_id TEXT`).run(); await env.DB.batch([env.DB.prepare(`CREATE TABLE IF NOT EXISTS message_reactions (message_id TEXT NOT NULL,user_id TEXT NOT NULL,emoji TEXT NOT NULL,PRIMARY KEY (message_id,user_id,emoji))`), env.DB.prepare(`CREATE TABLE IF NOT EXISTS typing_indicators (conversation_id TEXT NOT NULL,user_id TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY (conversation_id,user_id))`), env.DB.prepare(`CREATE TABLE IF NOT EXISTS message_search_grants (searcher_id TEXT NOT NULL,target_user_id TEXT NOT NULL,expires_at TEXT NOT NULL,PRIMARY KEY (searcher_id,target_user_id))`)]); }
async function reactions(env: Env, messageId: string) { const rows = await env.DB.prepare(`SELECT emoji, user_id FROM message_reactions WHERE message_id = ? ORDER BY emoji`).bind(messageId).all<any>(); const map = new Map<string, number[]>(); for (const row of rows.results) { if (!map.has(row.emoji)) map.set(row.emoji, []); map.get(row.emoji)!.push(Number(row.user_id)); } return Array.from(map, ([emoji, userIds]) => ({ emoji, count: userIds.length, userIds })); }
async function messageObject(env: Env, row: any) { const sender = await env.DB.prepare(`SELECT * FROM users WHERE id = ? LIMIT 1`).bind(row.sender_id).first<any>(); return { id: Number(row.id), conversationId: String(row.conversation_id), senderId: Number(row.sender_id), sender: sender ? publicUser(sender) : null, content: row.body, editedAt: null, createdAt: row.created_at, readAt: (await env.DB.prepare(`SELECT MIN(read_at) AS read_at FROM message_reads WHERE message_id = ? AND user_id != ?`).bind(row.id, row.sender_id).first<any>())?.read_at || null, reactions: await reactions(env, row.id) }; }
async function conversationObject(env: Env, conversationId: string, me: string) { const participants = await env.DB.prepare(`SELECT u.* FROM conversation_members cm JOIN users u ON u.id = cm.user_id WHERE cm.conversation_id = ?`).bind(conversationId).all<any>(); const last = await env.DB.prepare(`SELECT * FROM messages WHERE conversation_id = ? ORDER BY created_at DESC LIMIT 1`).bind(conversationId).first<any>(); const unread = await env.DB.prepare(`SELECT COUNT(*) AS count FROM messages WHERE conversation_id = ? AND sender_id != ?`).bind(conversationId, me).first<any>(); const conv = await env.DB.prepare(`SELECT * FROM conversations WHERE id = ?`).bind(conversationId).first<any>(); return { id: String(conversationId), participants: participants.results.map((u: any) => publicUser(u)), lastMessage: last ? await messageObject(env, last) : null, unreadCount: Number(unread?.count || 0), createdAt: conv?.created_at, updatedAt: conv?.updated_at }; }

async function postObject(env: Env, row: any, me: string) {
  const user = await env.DB.prepare(`SELECT * FROM users WHERE id = ? LIMIT 1`).bind(row.user_id).first<any>();
  const likes = await env.DB.prepare(`SELECT COUNT(*) AS count FROM post_likes WHERE post_id = ?`).bind(row.id).first<any>();
  const comments = await env.DB.prepare(`SELECT COUNT(*) AS count FROM post_comments WHERE post_id = ?`).bind(row.id).first<any>();
  const liked = await env.DB.prepare(`SELECT 1 FROM post_likes WHERE post_id = ? AND user_id = ? LIMIT 1`).bind(row.id, me).first<any>();
  const following = user && String(user.id) !== String(me) ? await env.DB.prepare(`SELECT 1 FROM follows WHERE follower_id = ? AND following_id = ? LIMIT 1`).bind(me, user.id).first<any>() : null;
  let repostOf: any = null;
  const repostMatch = String(row.content || '').match(/^\[PULSE_REPOST:([^\]]+)\](?:\n|\s)*(.*)$/s);
  if (repostMatch) { const original = await env.DB.prepare(`SELECT * FROM posts WHERE id = ? LIMIT 1`).bind(repostMatch[1]).first<any>(); if (original) { const originalUser = await env.DB.prepare(`SELECT * FROM users WHERE id = ? LIMIT 1`).bind(original.user_id).first<any>(); repostOf = { id: String(original.id), content: original.content, createdAt: original.created_at, user: originalUser ? publicUser(originalUser) : null, image: original.image_url || null, filter: original.filter || 'Normal', music: original.music_url ? { title: original.music_title, artist: original.music_artist, previewUrl: original.music_url } : null }; } }
  const media = (row.image_url || row.music_url || row.filter) ? { image: row.image_url || null, filter: row.filter || 'Normal', music: row.music_url ? { title: row.music_title || 'Unknown track', artist: row.music_artist || '', previewUrl: row.music_url } : null } : null;
  return { id: String(row.id), content: repostMatch ? (repostMatch[2] || '') : row.content, createdAt: row.created_at, user: user ? publicUser(user) : null, likeCount: Number(likes?.count || 0), commentCount: Number(comments?.count || 0), liked: !!liked, following: !!following, media, repostOf };
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders(request, env) });
    try {
      await ensureExtraTables(env);
      const url = new URL(request.url); const path = url.pathname.replace(/\/+$/, "") || "/";
      if (path === "/" || path === "/api/health" || path === "/api/healthz") return json({ status: "ok", service: "pulse-api" }, 200, request, env);
      if (path === "/api/auth/register" && request.method === "POST") { const body = await parseBody(request); const username = String(body.username || "").trim(); const displayName = String(body.displayName || "").trim(); const password = String(body.password || ""); if (username.length < 3 || username.length > 30 || displayName.length < 1 || displayName.length > 50 || password.length < 6) return error("Invalid input", 400, request, env); const existing = await env.DB.prepare(`SELECT id FROM users WHERE lower(username) = lower(?) LIMIT 1`).bind(username).first(); if (existing) return error("Username already taken", 400, request, env); const userId = id(); const passwordHash = await createPasswordHash(password); const now = new Date().toISOString(); await env.DB.prepare(`INSERT INTO users (id, username, email, password_hash, display_name, created_at, updated_at) VALUES (?, ?, NULL, ?, ?, ?, ?)`).bind(userId, username, passwordHash, displayName, now, now).run(); const sessionId = crypto.randomUUID(); const expires = new Date(Date.now() + SESSION_DAYS * 86400000).toISOString(); await env.DB.prepare(`INSERT INTO sessions (id, user_id, expires_at) VALUES (?, ?, ?)`).bind(sessionId, userId, expires).run(); const user = await env.DB.prepare(`SELECT * FROM users WHERE id = ?`).bind(userId).first<any>(); return json(publicUser(user, true), 201, request, env, { "Set-Cookie": sessionCookie(sessionId) }); }
      if (path === "/api/auth/login" && request.method === "POST") { const body = await parseBody(request); const username = String(body.username || "").trim(); const password = String(body.password || ""); const user = await env.DB.prepare(`SELECT * FROM users WHERE lower(username) = lower(?) LIMIT 1`).bind(username).first<any>(); if (!user || !(await verifyPassword(password, user.password_hash))) return error("Invalid credentials", 401, request, env); const sessionId = crypto.randomUUID(); const expires = new Date(Date.now() + SESSION_DAYS * 86400000).toISOString(); await env.DB.prepare(`INSERT INTO sessions (id, user_id, expires_at) VALUES (?, ?, ?)`).bind(sessionId, user.id, expires).run(); return json(publicUser(user, true), 200, request, env, { "Set-Cookie": sessionCookie(sessionId) }); }
      if (path === "/api/auth/change-password" && request.method === "POST") { const body = await parseBody(request); const currentPassword = String(body.currentPassword || ""); const newPassword = String(body.newPassword || ""); if (newPassword.length < 6) return error("New password must be at least 6 characters", 400, request, env); const user = await currentUser(request, env); if (!user) return error("Not authenticated", 401, request, env); if (!(await verifyPassword(currentPassword, user.password_hash))) return error("Current password is incorrect", 400, request, env); const passwordHash = await createPasswordHash(newPassword); await env.DB.prepare(`UPDATE users SET password_hash = ?, updated_at = ? WHERE id = ?`).bind(passwordHash, new Date().toISOString(), user.id).run(); return json({ ok: true }, 200, request, env); }
      if (path === "/api/auth/logout" && request.method === "POST") { const token = getCookie(request, SESSION_COOKIE); if (token) await env.DB.prepare(`DELETE FROM sessions WHERE id = ?`).bind(token).run(); return json({ ok: true }, 200, request, env, { "Set-Cookie": sessionCookie("", 0) }); }
      if (path === "/api/auth/me" && request.method === "GET") { const user = await requireUser(request, env); if (!user) return error("Not authenticated", 401, request, env); return json(publicUser(user, true), 200, request, env); }
      const me = await requireUser(request, env); if (!me) return error("Not authenticated", 401, request, env);
      if (path === "/api/users/me/peer" && request.method === "PATCH") { const body = await parseBody(request); const peerId = body.peerId ? String(body.peerId).slice(0, 200) : null; await env.DB.prepare(`UPDATE users SET peer_id = ?, updated_at = ? WHERE id = ?`).bind(peerId, new Date().toISOString(), me.id).run(); const updated = await env.DB.prepare(`SELECT * FROM users WHERE id = ?`).bind(me.id).first<any>(); return json(publicUser(updated, true), 200, request, env); }
      const readMatch = path.match(/^\/api\/conversations\/([^/]+)\/(?:read|mark-read)$/);
      if (readMatch && request.method === "POST") { const conversationId = readMatch[1]; const member = await env.DB.prepare(`SELECT 1 FROM conversation_members WHERE conversation_id = ? AND user_id = ? LIMIT 1`).bind(conversationId, me.id).first<any>(); if (!member) return error("Conversation not found", 404, request, env); const now = new Date().toISOString(); await env.DB.prepare(`INSERT OR REPLACE INTO message_reads (message_id, user_id, read_at) SELECT id, ?, ? FROM messages WHERE conversation_id = ? AND sender_id != ?`).bind(me.id, now, conversationId, me.id).run(); return json({ ok: true, readAt: now }, 200, request, env); }
      if (path === "/api/users" && request.method === "GET") { const search = (url.searchParams.get("search") || "").trim(); const rows = search ? await env.DB.prepare(`SELECT * FROM users WHERE (lower(username) LIKE lower(?) OR lower(display_name) LIKE lower(?)) ORDER BY username LIMIT 20`).bind(`%${search}%`, `%${search}%`).all<any>() : await env.DB.prepare(`SELECT * FROM users ORDER BY username LIMIT 30`).all<any>(); if (search) { const exact = await env.DB.prepare(`SELECT id FROM users WHERE lower(username) = lower(?) LIMIT 1`).bind(search).first<any>(); if (exact && String(exact.id) !== String(me.id)) await env.DB.prepare(`INSERT OR REPLACE INTO message_search_grants (searcher_id,target_user_id,expires_at) VALUES (?,?,?)`).bind(me.id, exact.id, new Date(Date.now() + 10 * 60 * 1000).toISOString()).run(); } return json(rows.results.map((u: any) => publicUser(u)), 200, request, env); }
      if (path === "/api/users/me" && request.method === "GET") return json(publicUser(me, true), 200, request, env);
      if (path === "/api/users/me" && request.method === "PATCH") { const body = await parseBody(request); const displayName = body.displayName !== undefined ? String(body.displayName).trim() : me.display_name; const bio = body.bio !== undefined ? String(body.bio).trim().slice(0, 200) : (me.bio ?? null); const avatarUrl = body.avatarUrl !== undefined ? String(body.avatarUrl) : me.avatar_url; const messageSearchOnly = body.messageSearchOnly !== undefined ? (body.messageSearchOnly ? 1 : 0) : Number(me.message_search_only || 0); if (avatarUrl && avatarUrl.length > 1200000) return error("Avatar image is too large", 400, request, env); await env.DB.prepare(`UPDATE users SET display_name = ?, avatar_url = ?, bio = ?, message_search_only = ?, updated_at = ? WHERE id = ?`).bind(displayName, avatarUrl, bio, messageSearchOnly, new Date().toISOString(), me.id).run(); const updated = await env.DB.prepare(`SELECT * FROM users WHERE id = ?`).bind(me.id).first<any>(); return json(publicUser(updated, true), 200, request, env); }
      if (path === "/api/users/me/heartbeat" && request.method === "POST") { const now = new Date().toISOString(); await env.DB.prepare(`UPDATE users SET last_seen_at = ? WHERE id = ?`).bind(now, me.id).run(); return json({ ok: true, lastSeen: now }, 200, request, env); }

      const userFollowMatch = path.match(/^\/api\/users\/([^/]+)\/follow$/);
      if (userFollowMatch) { const targetId = String(userFollowMatch[1]); const target = await env.DB.prepare(`SELECT * FROM users WHERE id = ? OR CAST(id AS REAL) = ? LIMIT 1`).bind(targetId, Number(targetId)).first<any>(); if (!target) return error("User not found", 404, request, env); if (String(target.id) === String(me.id)) return error("You cannot follow yourself", 400, request, env); if (request.method === "POST") await env.DB.prepare(`INSERT OR IGNORE INTO follows (follower_id, following_id, created_at) VALUES (?, ?, ?)`).bind(me.id, target.id, new Date().toISOString()).run(); else if (request.method === "DELETE") await env.DB.prepare(`DELETE FROM follows WHERE follower_id = ? AND following_id = ?`).bind(me.id, target.id).run(); else return error("Method not allowed", 405, request, env); const following = await env.DB.prepare(`SELECT 1 FROM follows WHERE follower_id = ? AND following_id = ? LIMIT 1`).bind(me.id, target.id).first<any>(); return json({ following: !!following }, 200, request, env); }
      const userProfileMatch = path.match(/^\/api\/users\/([^/]+)\/profile$/);
      if (userProfileMatch && request.method === "GET") { const targetId = String(userProfileMatch[1]); const target = await env.DB.prepare(`SELECT * FROM users WHERE id = ? OR CAST(id AS REAL) = ? LIMIT 1`).bind(targetId, Number(targetId)).first<any>(); if (!target) return error("User not found", 404, request, env); const followers = await env.DB.prepare(`SELECT COUNT(*) AS count FROM follows WHERE following_id = ?`).bind(target.id).first<any>(); const followingCount = await env.DB.prepare(`SELECT COUNT(*) AS count FROM follows WHERE follower_id = ?`).bind(target.id).first<any>(); const isFollowing = await env.DB.prepare(`SELECT 1 FROM follows WHERE follower_id = ? AND following_id = ? LIMIT 1`).bind(me.id, target.id).first<any>(); return json({ user: publicUser(target), followers: Number(followers?.count || 0), following: Number(followingCount?.count || 0), isFollowing: !!isFollowing }, 200, request, env); }

      if (path === "/api/feed" && request.method === "GET") { const mode = url.searchParams.get("mode") || "for-you"; let rows; if (mode === "following") rows = await env.DB.prepare(`SELECT p.* FROM posts p WHERE p.user_id = ? OR p.user_id IN (SELECT following_id FROM follows WHERE follower_id = ?) ORDER BY p.created_at DESC LIMIT 50`).bind(me.id, me.id).all<any>(); else if (mode === "popular") rows = await env.DB.prepare(`SELECT p.*, (SELECT COUNT(*) FROM post_likes l WHERE l.post_id = p.id) AS like_score, (SELECT COUNT(*) FROM post_comments c WHERE c.post_id = p.id) AS comment_score FROM posts p ORDER BY like_score DESC, comment_score DESC, p.created_at DESC LIMIT 50`).all<any>(); else rows = await env.DB.prepare(`SELECT p.* FROM posts p ORDER BY p.created_at DESC LIMIT 50`).all<any>(); const result = await Promise.all(rows.results.map((row: any) => postObject(env, row, String(me.id)))); return json(result, 200, request, env); }

      if (path === "/api/posts" && request.method === "POST") { const body = await parseBody(request); const content = String(body.content || "").trim(); const imageUrl = body.imageUrl ? String(body.imageUrl) : null; const musicUrl = body.musicUrl ? String(body.musicUrl) : null; const musicTitle = body.musicTitle ? String(body.musicTitle).slice(0, 200) : null; const musicArtist = body.musicArtist ? String(body.musicArtist).slice(0, 200) : null; const filter = body.filter ? String(body.filter).slice(0, 80) : null; if (!content && !imageUrl && !musicUrl) return error("Post cannot be empty", 400, request, env); if (content.length > 500) return error("Post text is limited to 500 characters", 400, request, env); if (imageUrl && imageUrl.length > 1200000) return error("That photo is too large. Please choose a smaller image.", 400, request, env); if (imageUrl && !/^data:image\/(jpeg|jpg|png|webp|gif);base64,/i.test(imageUrl)) return error("Invalid image", 400, request, env); const postId = id(); const now = new Date().toISOString(); await env.DB.prepare(`INSERT INTO posts (id, user_id, content, image_url, music_url, music_title, music_artist, filter, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).bind(postId, me.id, content, imageUrl, musicUrl, musicTitle, musicArtist, filter, now, now).run(); const post = await env.DB.prepare(`SELECT * FROM posts WHERE id = ?`).bind(postId).first<any>(); return json(await postObject(env, post, String(me.id)), 201, request, env); }

      const repostMatch = path.match(/^\/api\/posts\/([^/]+)\/repost$/); if (repostMatch && request.method === "POST") { const originalId = repostMatch[1]; const original = await env.DB.prepare(`SELECT id FROM posts WHERE id = ? LIMIT 1`).bind(originalId).first<any>(); if (!original) return error("Post not found", 404, request, env); const body = await parseBody(request); const caption = String(body.caption || "").trim().slice(0, 500); const postId = id(); const now = new Date().toISOString(); await env.DB.prepare(`INSERT INTO posts (id, user_id, content, created_at, updated_at) VALUES (?, ?, ?, ?, ?)`).bind(postId, me.id, `[PULSE_REPOST:${originalId}]${caption ? `\n${caption}` : ''}`, now, now).run(); const post = await env.DB.prepare(`SELECT * FROM posts WHERE id = ?`).bind(postId).first<any>(); return json(await postObject(env, post, String(me.id)), 201, request, env); }

      const postLikeMatch = path.match(/^\/api\/posts\/([^/]+)\/like$/); if (postLikeMatch) { const postId = postLikeMatch[1]; const post = await env.DB.prepare(`SELECT id FROM posts WHERE id = ? LIMIT 1`).bind(postId).first<any>(); if (!post) return error("Post not found", 404, request, env); if (request.method === "POST") await env.DB.prepare(`INSERT OR IGNORE INTO post_likes (post_id, user_id, created_at) VALUES (?, ?, ?)`).bind(postId, me.id, new Date().toISOString()).run(); else if (request.method === "DELETE") await env.DB.prepare(`DELETE FROM post_likes WHERE post_id = ? AND user_id = ?`).bind(postId, me.id).run(); else return error("Method not allowed", 405, request, env); const likes = await env.DB.prepare(`SELECT COUNT(*) AS count FROM post_likes WHERE post_id = ?`).bind(postId).first<any>(); return json({ liked: request.method === "POST", likeCount: Number(likes?.count || 0) }, 200, request, env); }

      const postCommentsMatch = path.match(/^\/api\/posts\/([^/]+)\/comments$/); if (postCommentsMatch) { const postId = postCommentsMatch[1]; const post = await env.DB.prepare(`SELECT id FROM posts WHERE id = ? LIMIT 1`).bind(postId).first<any>(); if (!post) return error("Post not found", 404, request, env); if (request.method === "GET") { const rows = await env.DB.prepare(`SELECT c.*, u.* FROM post_comments c JOIN users u ON u.id = c.user_id WHERE c.post_id = ? ORDER BY c.created_at ASC LIMIT 100`).bind(postId).all<any>(); return json(rows.results.map((r: any) => ({ id: String(r.id), content: r.content, createdAt: r.created_at, user: publicUser(r) })), 200, request, env); } if (request.method === "POST") { const body = await parseBody(request); const content = String(body.content || "").trim(); if (!content || content.length > 300) return error("Comments must be between 1 and 300 characters", 400, request, env); const commentId = id(); const now = new Date().toISOString(); await env.DB.prepare(`INSERT INTO post_comments (id, post_id, user_id, content, created_at) VALUES (?, ?, ?, ?, ?)`).bind(commentId, postId, me.id, content, now).run(); const row = await env.DB.prepare(`SELECT c.*, u.* FROM post_comments c JOIN users u ON u.id = c.user_id WHERE c.id = ?`).bind(commentId).first<any>(); return json({ id: String(row.id), content: row.content, createdAt: row.created_at, user: publicUser(row) }, 201, request, env); } return error("Method not allowed", 405, request, env); }

      if (path === "/api/conversations" && request.method === "GET") { const rows = await env.DB.prepare(`SELECT conversation_id FROM conversation_members WHERE user_id = ?`).bind(me.id).all<any>(); const result = await Promise.all(rows.results.map((r: any) => conversationObject(env, r.conversation_id, me.id))); result.sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()); return json(result, 200, request, env); }
      if (path === "/api/conversations" && request.method === "POST") { const body = await parseBody(request); const participantId = String(body.participantId || ""); const participant = await env.DB.prepare(`SELECT * FROM users WHERE id = ? OR CAST(id AS REAL) = ? LIMIT 1`).bind(participantId, Number(participantId)).first<any>(); if (!participant) return error("Invalid participant", 400, request, env); const resolvedParticipantId = String(participant.id); const existing = await env.DB.prepare(`SELECT a.conversation_id FROM conversation_members a JOIN conversation_members b ON a.conversation_id = b.conversation_id WHERE a.user_id = ? AND b.user_id = ? LIMIT 1`).bind(me.id, resolvedParticipantId).first<any>(); let convId = existing?.conversation_id; if (!convId && participant.message_search_only) { const grant = await env.DB.prepare(`SELECT 1 FROM message_search_grants WHERE searcher_id = ? AND target_user_id = ? AND expires_at > ? LIMIT 1`).bind(me.id, resolvedParticipantId, new Date().toISOString()).first<any>(); if (!grant) return error("This user only accepts new messages after you search their exact username.", 403, request, env); } if (!convId) { convId = id(); const now = new Date().toISOString(); await env.DB.batch([env.DB.prepare(`INSERT INTO conversations (id, created_at, updated_at) VALUES (?, ?, ?)`).bind(convId, now, now), env.DB.prepare(`INSERT INTO conversation_members (conversation_id, user_id) VALUES (?, ?), (?, ?)`).bind(convId, me.id, convId, resolvedParticipantId)]); } return json(await conversationObject(env, convId, me.id), 201, request, env); }
      const convMatch = path.match(/^\/api\/conversations\/([^/]+)$/); if (convMatch && request.method === "GET") { const convId = convMatch[1]; const member = await env.DB.prepare(`SELECT 1 FROM conversation_members WHERE conversation_id = ? AND user_id = ?`).bind(convId, me.id).first(); if (!member) return error("Conversation not found", 404, request, env); return json(await conversationObject(env, convId, me.id), 200, request, env); }
      const typingMatch = path.match(/^\/api\/conversations\/([^/]+)\/typing$/); if (typingMatch && request.method === "POST") { const body = await parseBody(request); const convId = typingMatch[1]; if (body.isTyping) await env.DB.prepare(`INSERT INTO typing_indicators (conversation_id, user_id, updated_at) VALUES (?, ?, ?) ON CONFLICT(conversation_id,user_id) DO UPDATE SET updated_at=excluded.updated_at`).bind(convId, me.id, new Date().toISOString()).run(); else await env.DB.prepare(`DELETE FROM typing_indicators WHERE conversation_id = ? AND user_id = ?`).bind(convId, me.id).run(); return json({ ok: true }, 200, request, env); }
      const typingStatusMatch = path.match(/^\/api\/conversations\/([^/]+)\/typing-status$/); if (typingStatusMatch && request.method === "GET") { const rows = await env.DB.prepare(`SELECT u.* FROM typing_indicators t JOIN users u ON u.id=t.user_id WHERE t.conversation_id=? AND t.user_id != ? AND t.updated_at > ?`).bind(typingStatusMatch[1], me.id, new Date(Date.now() - 5000).toISOString()).all<any>(); return json(rows.results.map((u: any) => ({ userId: Number(u.id), username: u.username, displayName: u.display_name })), 200, request, env); }
      const messagesMatch = path.match(/^\/api\/conversations\/([^/]+)\/messages$/); if (messagesMatch) { const convId = messagesMatch[1]; const member = await env.DB.prepare(`SELECT 1 FROM conversation_members WHERE conversation_id = ? AND user_id = ?`).bind(convId, me.id).first(); if (!member) return error("Conversation not found", 404, request, env); if (request.method === "GET") { const limit = Math.min(Math.max(Number(url.searchParams.get("limit") || 50), 1), 100); const before = url.searchParams.get("before"); const rows = before ? await env.DB.prepare(`SELECT * FROM messages WHERE conversation_id = ? AND CAST(id AS INTEGER) < CAST(? AS INTEGER) ORDER BY created_at DESC LIMIT ?`).bind(convId, before, limit).all<any>() : await env.DB.prepare(`SELECT * FROM messages WHERE conversation_id = ? ORDER BY created_at DESC LIMIT ?`).bind(convId, limit).all<any>(); const result = await Promise.all(rows.results.reverse().map((r: any) => messageObject(env, r))); return json(result, 200, request, env); } if (request.method === "POST") { const body = await parseBody(request); const content = String(body.content || "").trim(); if (!content) return error("Message cannot be empty", 400, request, env); const messageId = id(); const now = new Date().toISOString(); await env.DB.batch([env.DB.prepare(`INSERT INTO messages (id, conversation_id, sender_id, body, created_at) VALUES (?, ?, ?, ?, ?)`).bind(messageId, convId, me.id, content, now), env.DB.prepare(`UPDATE conversations SET updated_at = ? WHERE id = ?`).bind(now, convId)]); const msg = await env.DB.prepare(`SELECT * FROM messages WHERE id = ?`).bind(messageId).first<any>(); return json(await messageObject(env, msg), 201, request, env); } }
      const reactionMatch = path.match(/^\/api\/conversations\/([^/]+)\/messages\/([^/]+)\/reactions(?:\/([^/]+))?$/); if (reactionMatch) { const msgId = reactionMatch[2]; if (request.method === "POST") { const body = await parseBody(request); const emoji = String(body.emoji || ""); if (!emoji) return error("Invalid reaction", 400, request, env); await env.DB.prepare(`INSERT OR IGNORE INTO message_reactions (message_id,user_id,emoji) VALUES (?,?,?)`).bind(msgId, me.id, emoji).run(); } else if (request.method === "DELETE" && reactionMatch[3]) await env.DB.prepare(`DELETE FROM message_reactions WHERE message_id=? AND user_id=? AND emoji=?`).bind(msgId, me.id, decodeURIComponent(reactionMatch[3])).run(); const msg = await env.DB.prepare(`SELECT * FROM messages WHERE id=?`).bind(msgId).first<any>(); if (!msg) return error("Message not found", 404, request, env); return json(await messageObject(env, msg), 200, request, env); }
      const editMatch = path.match(/^\/api\/conversations\/([^/]+)\/messages\/([^/]+)$/); if (editMatch && request.method === "PATCH") { const body = await parseBody(request); const msg = await env.DB.prepare(`SELECT * FROM messages WHERE id=? AND conversation_id=?`).bind(editMatch[2], editMatch[1]).first<any>(); if (!msg || String(msg.sender_id) !== String(me.id)) return error("Forbidden", 403, request, env); const content = String(body.content || "").trim(); if (!content) return error("Message cannot be empty", 400, request, env); await env.DB.prepare(`UPDATE messages SET body=? WHERE id=?`).bind(content, editMatch[2]).run(); return json(await messageObject(env, { ...msg, body: content }), 200, request, env); }
      if (editMatch && request.method === "DELETE") { const msg = await env.DB.prepare(`SELECT * FROM messages WHERE id=? AND conversation_id=?`).bind(editMatch[2], editMatch[1]).first<any>(); if (!msg || String(msg.sender_id) !== String(me.id)) return error("Forbidden", 403, request, env); await env.DB.prepare(`DELETE FROM messages WHERE id=?`).bind(editMatch[2]).run(); return json({ ok: true }, 200, request, env); }
      if (path === "/api/messages/search" && request.method === "GET") { const q = (url.searchParams.get("q") || "").trim(); if (!q) return json([], 200, request, env); const rows = await env.DB.prepare(`SELECT m.* FROM messages m JOIN conversation_members cm ON cm.conversation_id=m.conversation_id WHERE cm.user_id=? AND lower(m.body) LIKE lower(?) ORDER BY m.created_at DESC LIMIT 20`).bind(me.id, `%${q}%`).all<any>(); const result = await Promise.all(rows.results.map(async (r: any) => ({ message: await messageObject(env, r), conversationId: Number(r.conversation_id) }))); return json(result, 200, request, env); }
      return error("Not found", 404, request, env);
    } catch (e) { console.error(e); return error("Server error", 500, request, env); }
  },
};
