import { useState } from "react";
import { Message, useDeleteMessage, useEditMessage, useAddReaction, useRemoveReaction, useGetMe, getGetMeQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { formatTime, getInitials } from "@/lib/utils";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { BadgeList } from "@/lib/badges";
import { Pencil, Trash2, SmilePlus, X, Check, Paperclip, Download, CheckCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

const COMMON_EMOJIS = ["👍", "❤️", "😂", "😮", "😢", "🔥"];
type MediaType = "image" | "gif" | "sticker" | "file" | "text";
function getMediaType(content: string): MediaType { const trimmed = content.trim(); if (trimmed.startsWith("pulse-file:")) return "file"; const isSingleEmoji = /^(\p{Emoji_Presentation}|\p{Emoji}\uFE0F)(\u200D(\p{Emoji_Presentation}|\p{Emoji}\uFE0F))*$/u.test(trimmed); if (isSingleEmoji) return "sticker"; if (/^https?:\/\/.+\.gif(\?.*)?$/i.test(trimmed) || trimmed.includes("giphy.com/media/") || trimmed.includes("media.tenor.com/") || trimmed.includes("media1.tenor.com/") || trimmed.includes("media2.tenor.com/")) return "gif"; if (/^https?:\/\/.+\.(jpg|jpeg|png|webp|svg|avif)(\?.*)?$/i.test(trimmed) || /^data:image\//i.test(trimmed)) return "image"; return "text"; }
function parseFile(content: string) { try { return JSON.parse(content.slice("pulse-file:".length)) as { name: string; type: string; data: string }; } catch { return null; } }
function Status({ message }: { message: any }) { const read = !!(message.readAt || message.read_at || message.seenAt || message.seen_at); return <span title={read ? "Read" : "Delivered"} className={`inline-flex items-center ml-0.5 ${read ? "text-cyan-300 drop-shadow-[0_0_5px_rgba(34,211,238,.95)]" : "text-muted-foreground"}`}><CheckCheck className="w-3.5 h-3.5 stroke-[2.6]" /></span>; }

export function MessageBubble({ message, isOwn, showAvatar }: { message: Message, isOwn: boolean, showAvatar: boolean }) {
  const [isHovered, setIsHovered] = useState(false); const [isEditing, setIsEditing] = useState(false); const [editContent, setEditContent] = useState(message.content); const queryClient = useQueryClient();
  const { data: currentUser } = useGetMe({ query: { staleTime: Infinity, refetchOnWindowFocus: false, queryKey: getGetMeQueryKey() } });
  const deleteMessage = useDeleteMessage(); const editMessage = useEditMessage(); const addReaction = useAddReaction(); const removeReaction = useRemoveReaction();
  const handleEdit = () => { if (!editContent.trim() || editContent === message.content) { setIsEditing(false); return; } editMessage.mutate({ conversationId: message.conversationId, messageId: message.id, data: { content: editContent } }, { onSuccess: () => { setIsEditing(false); queryClient.invalidateQueries({ queryKey: [`/api/conversations/${message.conversationId}/messages`] }); } }); };
  const handleDelete = () => { if (confirm("Are you sure you want to delete this message?")) deleteMessage.mutate({ conversationId: message.conversationId, messageId: message.id }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: [`/api/conversations/${message.conversationId}/messages`] }); queryClient.invalidateQueries({ queryKey: ["/api/conversations"] }); } }); };
  const toggleReaction = (emoji: string) => { const hasReacted = message.reactions.some(r => r.emoji === emoji && currentUser && r.userIds.includes(currentUser.id)); if (hasReacted) removeReaction.mutate({ conversationId: message.conversationId, messageId: message.id, emoji }, { onSuccess: () => queryClient.invalidateQueries({ queryKey: [`/api/conversations/${message.conversationId}/messages`] }) }); else addReaction.mutate({ conversationId: message.conversationId, messageId: message.id, data: { emoji } }, { onSuccess: () => queryClient.invalidateQueries({ queryKey: [`/api/conversations/${message.conversationId}/messages`] }) }); };
  const stamp = (muted = false) => <div className={`text-[10px] mt-1 flex items-center ${isOwn ? "justify-end" : "justify-start"} gap-1 ${muted ? "opacity-50" : "opacity-60"} ${isOwn ? "text-primary-foreground" : "text-muted-foreground"}`}>{message.editedAt && <span>(edited)</span>}<span>{formatTime(message.createdAt)}</span>{isOwn && <Status message={message} />}</div>;

  return <div className={`flex items-end gap-2 w-full group ${isOwn ? "flex-row-reverse" : "flex-row"}`} onMouseEnter={() => setIsHovered(true)} onMouseLeave={() => setIsHovered(false)}>
    <div className="w-8 flex-shrink-0">{!isOwn && showAvatar && <Avatar className="w-8 h-8 select-none"><AvatarImage src={message.sender?.avatarUrl || ""} /><AvatarFallback className="text-[10px]">{getInitials(message.sender?.displayName || "?")}</AvatarFallback></Avatar>}</div>
    <div className={`flex flex-col gap-1 max-w-[70%] ${isOwn ? "items-end" : "items-start"}`}>
      {!isOwn && showAvatar && <div className="flex items-center gap-1.5 ml-1 max-w-full"><span className="text-xs text-muted-foreground truncate">{message.sender?.displayName}</span><BadgeList user={message.sender || {}} compact /></div>}
      <div className="flex items-center gap-2 w-full group/actions">
        {isOwn && isHovered && !isEditing && <div className="flex items-center gap-1 opacity-0 group-hover/actions:opacity-100 transition-opacity mr-1"><Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground" onClick={() => setIsEditing(true)}><Pencil className="w-3.5 h-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-destructive" onClick={handleDelete}><Trash2 className="w-3.5 h-3.5" /></Button></div>}
        <div className="relative group/bubble">{isEditing ? <div className="flex items-center gap-2 bg-secondary p-2 rounded-2xl"><input autoFocus value={editContent} onChange={e => setEditContent(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleEdit(); } if (e.key === 'Escape') { setIsEditing(false); setEditContent(message.content); } }} className="bg-transparent border-none outline-none text-sm text-foreground min-w-[200px]" /><Button size="icon" variant="ghost" className="h-6 w-6 text-green-500" onClick={handleEdit}><Check className="w-4 h-4" /></Button><Button size="icon" variant="ghost" className="h-6 w-6 text-destructive" onClick={() => { setIsEditing(false); setEditContent(message.content); }}><X className="w-4 h-4" /></Button></div> : (() => {
          const mediaType = getMediaType(message.content);
          if (mediaType === "sticker") return <div className="relative select-none"><span className="text-5xl leading-none">{message.content.trim()}</span>{stamp(true)}</div>;
          if (mediaType === "file") { const file = parseFile(message.content); if (!file) return null; if (file.type.startsWith("image/")) return <div className="relative"><a href={file.data} download={file.name} className="block rounded-2xl overflow-hidden max-w-[300px]"><img src={file.data} alt={file.name} className="w-full object-cover block max-h-80" loading="lazy" /></a><div className="flex items-center gap-2 mt-1 text-xs text-muted-foreground"><span className="truncate max-w-[220px]">{file.name}</span><a href={file.data} download={file.name} title="Download"><Download className="w-3.5 h-3.5" /></a></div>{isOwn && <Status message={message} />}</div>; return <div><a href={file.data} download={file.name} className="flex items-center gap-3 px-4 py-3 rounded-2xl bg-secondary hover:bg-secondary/80 border border-border max-w-[300px] transition-colors"><Paperclip className="w-5 h-5 text-primary shrink-0" /><span className="text-sm font-medium truncate">{file.name}</span><Download className="w-4 h-4 ml-auto shrink-0 text-muted-foreground" /></a>{isOwn && <div className="flex justify-end mt-1"><Status message={message} /></div>}</div>; }
          if (mediaType === "image" || mediaType === "gif") return <div className="relative"><div className={`rounded-2xl overflow-hidden max-w-[260px] ${isOwn ? "rounded-br-sm" : "rounded-bl-sm"}`}><img src={message.content.trim()} alt={mediaType === "gif" ? "GIF" : "Image"} className="w-full object-cover block" loading="lazy" onError={e => { (e.target as HTMLImageElement).style.display = "none"; }} /></div>{stamp(true)}</div>;
          return <div className={`px-4 py-2.5 rounded-2xl text-[15px] leading-relaxed relative ${isOwn ? "bg-primary text-primary-foreground rounded-br-sm" : "bg-secondary text-foreground rounded-bl-sm"}`}><p className="whitespace-pre-wrap break-words">{message.content}</p>{stamp()}</div>;
        })()}
        {!isEditing && isHovered && <div className={`absolute -top-10 ${isOwn ? "right-0" : "left-0"} bg-card border border-border shadow-xl rounded-full px-2 py-1.5 flex items-center gap-1 z-20 animate-in fade-in zoom-in-95 duration-100`}>{COMMON_EMOJIS.map(emoji => <button key={emoji} onClick={() => toggleReaction(emoji)} className="hover:bg-secondary p-1 rounded-full text-lg transition-transform hover:scale-125">{emoji}</button>)}</div>}
        </div>
        {!isOwn && isHovered && !isEditing && <div className="flex items-center gap-1 opacity-0 group-hover/actions:opacity-100 transition-opacity ml-1"><Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground"><SmilePlus className="w-3.5 h-3.5" /></Button></div>}
      </div>
      {message.reactions && message.reactions.length > 0 && <div className={`flex flex-wrap gap-1 mt-0.5 max-w-full ${isOwn ? "justify-end" : "justify-start"}`}>{message.reactions.map(reaction => { const hasReacted = currentUser && reaction.userIds.includes(currentUser.id); return <button key={reaction.emoji} onClick={() => toggleReaction(reaction.emoji)} className={`flex items-center gap-1 text-[11px] px-1.5 py-0.5 rounded-full border transition-colors ${hasReacted ? "bg-primary/20 border-primary/30 text-primary" : "bg-card border-border hover:bg-secondary text-muted-foreground"}`}><span>{reaction.emoji}</span><span className="font-semibold">{reaction.count}</span></button>; })}</div>}
    </div>
  </div>;
}
