import { useEffect, useRef, useState } from "react";
import { Phone, PhoneOff, Mic, MicOff, Video, VideoOff, X } from "lucide-react";
import { useAuth } from "@/hooks/use-auth";

const PEER_SCRIPT = "https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js";
const API = "https://pulse-api-proxy.joeldavidengelman.workers.dev";
type CallMode = "voice" | "video";
type CallTarget = { id: number; displayName: string; username: string; avatarUrl?: string | null; peerId?: string | null };
type ActiveCall = { remote: CallTarget; incoming: boolean; mode: CallMode };
declare global { interface Window { Peer?: any } }

function loadPeer(): Promise<any> { if (window.Peer) return Promise.resolve(window.Peer); return new Promise((resolve,reject)=>{ const e=document.querySelector<HTMLScriptElement>('script[data-pulse-peerjs]'); if(e){e.addEventListener("load",()=>resolve(window.Peer));e.addEventListener("error",reject);return;} const s=document.createElement("script");s.src=PEER_SCRIPT;s.async=true;s.dataset.pulsePeerjs="true";s.onload=()=>window.Peer?resolve(window.Peer):reject(new Error("Calling library failed to load"));s.onerror=()=>reject(new Error("Calling library failed to load"));document.head.appendChild(s); }); }
function stopStream(s:MediaStream|null){s?.getTracks().forEach(t=>t.stop())}
export function startPulseCall(target:CallTarget,mode:CallMode="voice"){window.dispatchEvent(new CustomEvent("pulse:start-call",{detail:{target,mode}}))}

export function CallManager(){
 const {user}=useAuth(); const peerRef=useRef<any>(null); const localRef=useRef<MediaStream|null>(null); const callRef=useRef<any>(null); const audioRef=useRef<HTMLAudioElement>(null); const remoteVideoRef=useRef<HTMLVideoElement>(null); const localVideoRef=useRef<HTMLVideoElement>(null); const userRef=useRef(user);
 const [incoming,setIncoming]=useState<{target:CallTarget;mode:CallMode}|null>(null),[active,setActive]=useState<ActiveCall|null>(null),[connecting,setConnecting]=useState(false),[muted,setMuted]=useState(false),[cameraOff,setCameraOff]=useState(false),[error,setError]=useState("");
 useEffect(()=>{userRef.current=user},[user]);
 const cleanup=()=>{try{callRef.current?.close()}catch{}callRef.current=null;stopStream(localRef.current);localRef.current=null;if(audioRef.current)audioRef.current.srcObject=null;if(remoteVideoRef.current)remoteVideoRef.current.srcObject=null;if(localVideoRef.current)localVideoRef.current.srcObject=null;setIncoming(null);setActive(null);setConnecting(false);setMuted(false);setCameraOff(false)};
 const attach=(s:MediaStream,m:CallMode)=>{if(audioRef.current){audioRef.current.srcObject=s;void audioRef.current.play().catch(()=>{})}if(m==="video"&&remoteVideoRef.current){remoteVideoRef.current.srcObject=s;void remoteVideoRef.current.play().catch(()=>{})}};
 const registerPeer=async(id:string)=>{try{await fetch(`${API}/api/users/me/peer`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({peerId:id})})}catch(e){console.warn("Pulse could not register call address",e)}};
 const getPeer=async()=>{if(peerRef.current&&!peerRef.current.destroyed)return peerRef.current;const Peer=await loadPeer();if(!userRef.current)throw new Error("Not signed in");const peer=new Peer({host:"0.peerjs.com",port:443,path:"/",secure:true,debug:0});
  peer.on("open",(id:string)=>{console.info("[Pulse] calling ready",id);void registerPeer(id);setError("")});
  peer.on("error",(e:any)=>{console.error("[Pulse] peer error",e);if(e?.type!=="disconnected")setError(e?.type==="network"?"Could not reach the calling server. Check your internet connection.":e?.type==="peer-unavailable"?"That person is not currently available for calls.":"Could not connect to Pulse calling.")});
  peer.on("disconnected",()=>{try{peer.reconnect()}catch{}});
  peer.on("call",(call:any)=>{if(callRef.current){call.close();return;}const m=call.metadata?.from;const target:CallTarget=m?{id:Number(m.id),displayName:m.displayName||"Pulse user",username:m.username||"",avatarUrl:m.avatarUrl||null,peerId:call.peer}:{id:0,displayName:"Pulse user",username:"",peerId:call.peer};const mode:CallMode=call.metadata?.mode==="video"?"video":"voice";callRef.current=call;setIncoming({target,mode});call.on("close",()=>{if(callRef.current===call)cleanup()});call.on("error",()=>{if(callRef.current===call){setError("The incoming call failed.");cleanup()}})});
  peerRef.current=peer;return peer;
 };
 useEffect(()=>{if(!user?.id)return;let dead=false;void getPeer().catch(e=>{if(!dead)setError(e.message||"Could not connect to calling.")});const onStart=(e:Event)=>{const d=(e as CustomEvent).detail;if(d?.target&&d.target.id!==user.id&&!callRef.current)void beginCall(d.target,d.mode||"voice")};window.addEventListener("pulse:start-call",onStart);return()=>{dead=true;window.removeEventListener("pulse:start-call",onStart);cleanup();try{peerRef.current?.destroy()}catch{}peerRef.current=null}},[user?.id]);
 const beginCall=async(target:CallTarget,mode:CallMode)=>{setError("");setConnecting(true);try{const peer=await getPeer();if(!peer.open)await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("Could not connect to calling.")),10000);peer.once("open",()=>{clearTimeout(timer);resolve()});peer.once("error",reject)});if(!target.peerId)throw new Error("That person is not currently available for calls. Ask them to refresh Pulse first.");const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:mode==="video"});localRef.current=stream;if(mode==="video"&&localVideoRef.current){localVideoRef.current.srcObject=stream;void localVideoRef.current.play().catch(()=>{})}const call=peer.call(target.peerId,stream,{metadata:{from:{id:userRef.current!.id,displayName:userRef.current!.displayName,username:userRef.current!.username,avatarUrl:userRef.current!.avatarUrl},mode}});if(!call)throw new Error("That person is not currently available for calls.");callRef.current=call;setActive({remote:target,incoming:false,mode});call.on("stream",(s:MediaStream)=>{attach(s,mode);setConnecting(false)});call.on("close",cleanup);call.on("error",()=>{setError("The call could not connect. Make sure both people have Pulse open and refreshed.");cleanup()})}catch(e:any){setError(e?.message||"Could not connect to calling.");cleanup()}};
 const accept=async()=>{const call=callRef.current,r=incoming;if(!call||!r)return;setConnecting(true);try{const s=await navigator.mediaDevices.getUserMedia({audio:true,video:r.mode==="video"});localRef.current=s;call.answer(s);setIncoming(null);setActive({remote:r.target,incoming:true,mode:r.mode});call.on("stream",(rs:MediaStream)=>{attach(rs,r.mode);setConnecting(false)});call.on("close",cleanup);call.on("error",()=>{setError("The call ended unexpectedly.");cleanup()})}catch(e:any){setError(e?.message||"Microphone permission is required to answer.");cleanup()}};
 const hangup=()=>{try{callRef.current?.close()}catch{}cleanup()};const toggleMute=()=>{const n=!muted;localRef.current?.getAudioTracks().forEach(t=>t.enabled=!n);setMuted(n)};const toggleCamera=()=>{const n=!cameraOff;localRef.current?.getVideoTracks().forEach(t=>t.enabled=!n);setCameraOff(n)};
 if(!user)return null;return <><audio ref={audioRef} autoPlay playsInline/><div aria-live="assertive" className="fixed inset-x-0 top-0 z-[100] pointer-events-none">{incoming&&<div className="pointer-events-auto mx-auto mt-4 w-[min(420px,calc(100vw-2rem))] rounded-3xl border border-primary/30 bg-card shadow-2xl p-5"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-full bg-primary/10 text-primary grid place-items-center"><Phone className="w-5 h-5 animate-pulse"/></div><div className="flex-1"><p className="font-semibold">{incoming.target.displayName}</p><p className="text-sm text-muted-foreground">Incoming {incoming.mode} call · @{incoming.target.username}</p></div></div><div className="flex gap-2 mt-4"><button onClick={hangup} className="flex-1 h-11 rounded-xl bg-destructive/10 text-destructive font-semibold"><PhoneOff className="inline w-4 h-4 mr-2"/>Decline</button><button onClick={accept} disabled={connecting} className="flex-1 h-11 rounded-xl bg-primary text-primary-foreground font-semibold">{connecting?"Connecting…":<><Phone className="inline w-4 h-4 mr-2"/>Answer</>}</button></div></div>}</div>{active?.mode==="voice"&&<div className="fixed bottom-5 right-5 z-[75] w-[min(360px,calc(100vw-2rem))] rounded-3xl border border-border bg-card shadow-2xl p-5"><div className="flex items-center gap-3"><Phone className="text-primary"/><div className="flex-1"><p className="font-semibold">{active.remote.displayName}</p><p className="text-xs text-muted-foreground">{connecting?"Connecting…":"Voice call"}</p></div></div><div className="flex gap-2 mt-5"><button onClick={toggleMute} className="h-11 flex-1 rounded-xl bg-secondary">{muted?"Unmute":"Mute"}</button><button onClick={hangup} className="h-11 px-5 rounded-xl bg-destructive text-destructive-foreground"><PhoneOff/></button></div></div>}{active?.mode==="video"&&<div className="fixed inset-0 z-[70] bg-black/90 flex items-center justify-center"><video ref={remoteVideoRef} autoPlay playsInline className="w-full h-full object-contain"/><video ref={localVideoRef} autoPlay muted playsInline className="absolute right-5 top-5 w-40 aspect-video object-cover rounded-xl"/><div className="absolute bottom-5 flex gap-2"><button onClick={toggleMute} className="h-11 w-11 rounded-xl bg-white/10 text-white">{muted?<MicOff/>:<Mic/>}</button><button onClick={toggleCamera} className="h-11 w-11 rounded-xl bg-white/10 text-white">{cameraOff?<VideoOff/>:<Video/>}</button><button onClick={hangup} className="h-11 px-5 rounded-xl bg-red-600 text-white"><PhoneOff/></button></div></div>}{error&&<div className="fixed bottom-5 left-1/2 -translate-x-1/2 z-[110] flex items-center gap-3 rounded-2xl border border-destructive/30 bg-card px-4 py-3 shadow-2xl"><span className="text-sm text-destructive">{error}</span><button onClick={()=>setError("")}><X className="w-4 h-4"/></button></div>}</>;
}
